apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: test-and-build-reproducer-plr-
spec:
  taskRunTemplate:
    serviceAccountName: case03838507-pipeline-sa
  pipelineRef:
    name: test-and-build-reproducer
  params:
    - name: image-tag
      value: 4b33546b204c3882807d9ec636a363adc1223797
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: maven-settings
      configMap:
        name: maven-settings
    - name: maven-local-repo
      persistentvolumeclaim:
        claimName: maven-local-repo-pvc
